[package]
name = "competitive-programming-rs"
version = "0.1.0"
authors = ["kenkou.n@smail.com"]
description = "Competitive Programming Library in Rust"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/kenkoooo/competitive-programming-rs"
documentation = "https://kenkoooo.github.io/competitive-programming-rs/"
homepage = "https://github.com/kenkoooo/competitive-programming-rs"

[dependencies]
rand = "0.3.18"
