[package]
name = "competitive-programming-rs"
version = "0.1.7"
authors = ["kenkoooo"]
description = "Competitive Programming Library in Rust"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/kenkoooo/competitive-programming-rs"
documentation = "https://docs.rs/competitive-programming-rs"
homepage = "https://docs.rs/competitive-programming-rs"
exclude = ["assets/*"]

[dependencies]
rand = "0.4.2"
