[package]
name = "competitive-programming-rs"
version = "0.1.3"
authors = ["kenkoooo"]
description = "Competitive Programming Library in Rust"
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/kenkoooo/competitive-programming-rs"
documentation = "https://kenkoooo.github.io/competitive-programming-rs/"
homepage = "https://github.com/kenkoooo/competitive-programming-rs"
exclude = ["assets/*"]

[dependencies]
rand = "0.3.18"
